server:
  port: 9443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: secret
    key-password: password
    protocol: TLSv1.2
    
# To connect to CLI admin panel: $ ssh admin@localhost -p 2000
management:
  shell:
    auth:
      simple:
        user:
          name: admin
          password: password
          
graphql:
  server:
    mapping: /graphql
    corsEnabled: true
    suppressSpringResponseCodes: true
    query-key: query
    variables-key: variables
    uploadMaxFileSize: 128KB
    uploadMaxRequestSize: 128KB
  schema:
    clientMutationIdName: clientMutationId
    injectClientMutationId: true
    allowEmptyClientMutationId: false
    mutationInputArgumentName: input
    outputObjectNamePrefix: Payload
    inputObjectNamePrefix: Input
    schemaMutationObjectName: Mutation
