server:
  port: 9443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: secret
    key-password: password
    protocol: TLSv1.2
management:
  shell:
    auth:
      simple:
        user:
          name: admin
          password: password